name: Build and Release APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore android/app/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key -keypass "${{ secrets.KEY_PASSWORD }}" -storepass "${{ secrets.KEY_PASSWORD }}" -dname "CN=anbak, OU=IT, O=Sudax, L=Halfa, ST=SD, C=SD"

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEY_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=key" >> android/key.properties
          echo "storeFile=key.jks" >> android/key.properties

      - name: Build APK Release
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Janbak Delivery App v1.0.${{ github.run_number }}"
          files: build/app/outputs/flutter-apk/app-release.apk
          body: "نسخة جديدة موقعة وجاهزة للتثبيت المباشر لتطبيق جنبك."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
