name: Build Flutter APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true

      - name: Verify Directory and Get Dependencies
        run: |
          cd janbak_delivery
          flutter pub get

      - name: Build APK Release
        run: |
          cd janbak_delivery
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: janbak_delivery/build/app/outputs/flutter-apk/app-release.apk
