name: Build and Release APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK Debug
        run: |
          flutter build apk --debug \
            --android-skip-build-dependency-validation \
            --build-name=1.0.${{ github.run_number }} \
            --build-number=${{ github.run_number }}

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Janbak Delivery App v1.0.${{ github.run_number }}"
          files: build/app/outputs/flutter-apk/app-debug.apk
          body: "نسخة جديدة جاهزة للتثبيت المباشر لتطبيق جنبك."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
